// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "SWAPI Lambda API (GET)",
    "version": "1"
  },
  "paths": {
    "/api/people": {
      "get": {
        "summary": "Get People",
        "description": "Obtener personajes de Star Wars",
        "operationId": "getPeople.get./api/people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "string",
            "description": "Número de página (default: 1)",
            "required": false
          },
          {
            "in": "query",
            "name": "search",
            "type": "string",
            "description": "Término de búsqueda por nombre",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/favorites": {
      "get": {
        "summary": "Get Favorites",
        "description": "Obtener lista de favoritos",
        "operationId": "getFavorites.get./api/favorites",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "string",
            "description": "Número de página (default: 1)",
            "required": false
          },
          {
            "in": "query",
            "name": "pageSize",
            "type": "string",
            "description": "Cantidad de elementos por página (default: 10)",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/",
  "host": "y76a850dh4.execute-api.us-east-1.amazonaws.com"
};